services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '44444:3306'
    volumes:
      - ./mysql/db:/var/lib/mysql

networks:
  default:
    name: spring-hibernate
    driver: bridge